name: CI-Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

concurrency:
  group: ci_${{ github.ref }}
  cancel-in-progress: true

env:
  javaVersion: "17"
  javaDistribution: "liberica"

jobs:
  ci-platform-aws:
    runs-on: ubuntu-latest
    needs:
      - s3
    steps:
      - run: echo "CI-Build completed!"

  s3:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: ${{ env.javaVersion }}
          distribution: ${{ env.javaDistribution }}
      - run: |
          chmod +x gradlew
          ./gradlew :examples:s3:build
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: test-results_s3
          path: "**/build/reports/tests"
